### ISSUE TITLE
[Name]: Yashasvi Misra

### ISSUE THREAD

**Issue by yashasvimisra2798** [GHActUG/home#5]
### What you think ?

I am completely new to Github Actions, so I look forward to learning about Github actions and then leveraging it's use cases.

### Ready to Join the India Actions User Group ?

- [X] I agree to join the India Actions User Group

**Comment by ambilykk** [comment]
@yashasvimisra2798 expect delay in onboarding due to readiness issues. Will inform by 15th December about the group onboarding.

**Comment by ambilykk** [comment]
@yashasvimisra2798 please join the group at https://www.linkedin.com/groups/14157210/

**Comment by yashasvimisra2798** [comment]
> @yashasvimisra2798 please join the group at https://www.linkedin.com/groups/14157210/
> 

Joined, Thank you!
